theme: jekyll-theme-cayman
show_downloads: true
title: 铭
description: 你是否有一些难忘的话，想提醒自己时刻不要忘记，把它记录在'铭'上吧, '铭'会提醒你不要忘记.
downloadsurl:
  mac: https://github.com/assmdx/wordkit/releases/download/v1.0.2/wordkit-1.0.2.mac.dmg
  linux: https://github.com/assmdx/wordkit/releases/download/v1.0.2/wordkit-1.0.2.linux.AppImage
  windows: https://github.com/assmdx/wordkit/releases/download/v1.0.2/wordkit.1.0.2.windows.exe
